In [ ]:
# ƒast ƒourier transform
# The routine np.fft.fftfreq(n) returns an array giving the frequencies 
# of corresponding elements in the output. 
# The routine np.fft.fftshift(A) shifts transforms and their frequencies 
#to put the zero-frequency components in the middle, 
# and np.fft.ifftshift(A) undoes that shift.

# `signal = np.array([-2, 8, 6, 4, 1, 0, 3, 5], dtype=float)`
# `fourier = np.fft.fft(signal)`
# `n = signal.size`
# `timestep = 0.1`
# `freq = np.fft.fftfreq(n, d=timestep)`
# `freq`
# `array([ 0.  ,  1.25,  2.5 ,  3.75, -5.  , -3.75, -2.5 , -1.25])`



In [ ]:
signal = np.array(X.iloc[0])
f = np.fft.fft(signal)
n = signal.size
timestep = 0.02

In [ ]:
freq = np.fft.fftfreq(n, d=timestep)
freq

In [ ]:
# Shift the zero-frequency component to the center of the spectrum.
# This function swaps half-spaces for all axes listed (defaults to all). 
# Note that y[0] is the Nyquist component only if len(x) is even.

zf = np.fft.fftshift(freq)
zf

In [ ]:
spec, freqs, t, m = plt.specgram(zf, Fs=2, cmap='magma')
plt.colorbar()
plt.xlabel('Time MJD')
plt.ylabel('PDC_SAP Flux (e-/s)')

In [ ]:
3197/23

In [12]:
# SKlearn
# fft(a[, n, axis, norm])	Compute the one-dimensional discrete Fourier Transform.
# ifft(a[, n, axis, norm])	Compute the one-dimensional inverse discrete Fourier Transform.

In [1]:
import numpy as np

In [2]:
def dft(x):
    x = np.asarray(x, dtype=float)
    N = x.shape[0]
    n = np.arange(N)
    k = n.reshape((N, 1))
    M = np.exp(-2j * np.pi * k * n / N)
    return np.dot(M, x)

In [3]:
x = np.random.random(1024)
np.allclose(dft(x), np.fft.fft(x))

True

In [4]:
%timeit dft(x)
%timeit np.fft.fft(x)

77 ms ± 10.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
9.94 µs ± 1.37 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [5]:
def fft(x):
    x = np.asarray(x, dtype=float)
    N = x.shape[0]
    if N % 2 > 0:
        raise ValueError("must be a power of 2")
    elif N <= 2:
        return dft(x)
    else:
        X_even = fft(x[::2])
        X_odd = fft(x[1::2])
        terms = np.exp(-2j * np.pi * np.arange(N) / N)
        return np.concatenate([X_even + terms[:int(N/2)] * X_odd,
                               X_even + terms[int(N/2):] * X_odd])

In [6]:
x = np.random.random(1024)
np.allclose(fft(x), np.fft.fft(x))

True

In [7]:
%timeit dft(x)
%timeit fft(x)
%timeit np.fft.fft(x)

78 ms ± 27.1 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
26.3 ms ± 6.41 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
9.04 µs ± 2.07 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [9]:
# USing vectors instead of recursion
def fft_v(x):
    x = np.asarray(x, dtype=float)
    N = x.shape[0]
    if np.log2(N) % 1 > 0:
        raise ValueError("must be a power of 2")
        
    N_min = min(N, 2)
    
    n = np.arange(N_min)
    k = n[:, None]
    M = np.exp(-2j * np.pi * n * k / N_min)
    X = np.dot(M, x.reshape((N_min, -1)))
    
    while X.shape[0] < N:
            X_even = X[:, :int(X.shape[1] / 2)]
            X_odd = X[:, int(X.shape[1] / 2):]
            terms = np.exp(-1j * np.pi * np.arange(X.shape[0])
                            / X.shape[0])[:, None]
            X = np.vstack([X_even + terms * X_odd,
                           X_even - terms * X_odd])
    return X.ravel()

In [10]:
# verify
x = np.random.random(1024)
np.allclose(fft_v(x), np.fft.fft(x))

True

In [11]:
# vec is sig faster
%timeit fft(x)
%timeit fft_v(x)
%timeit np.fft.fft(x)

23.6 ms ± 2.21 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
534 µs ± 46.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
9.1 µs ± 1.63 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:

numpy.matrix.getH
x = np.matrix(np.arange(12).reshape((3,4)))

>>> z = x - 1j*x; z

matrix([[  0. +0.j,   1. -1.j,   2. -2.j,   3. -3.j],
        [  4. -4.j,   5. -5.j,   6. -6.j,   7. -7.j],
        [  8. -8.j,   9. -9.j,  10.-10.j,  11.-11.j]])

>>> z.getH()

matrix([[ 0. -0.j,  4. +4.j,  8. +8.j],
        [ 1. +1.j,  5. +5.j,  9. +9.j],
        [ 2. +2.j,  6. +6.j, 10.+10.j],
        [ 3. +3.j,  7. +7.j, 11.+11.j]])

# np.dot
dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])

# numpy.matrix.getA1
# Return self as a flattened ndarray.
# Equivalent to np.asarray(x).ravel()

>>> x = np.matrix(np.arange(12).reshape((3,4))); x

matrix([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

>>> x.getA1()

array([ 0,  1,  2, ...,  9, 10, 11])


>>> x = np.matrix(np.arange(12).reshape((3,4))); x

matrix([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

>>> x.getA()

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

>>> m = np.matrix([[1,2], [3,4]])
>>> m.flatten()
matrix([[1, 2, 3, 4]])
>>> m.flatten('F')
matrix([[1, 3, 2, 4]])